### ISSUE TITLE
【100 issues】前端基础学习

### ISSUE THREAD

**Issue by swiftwind0405** [swiftwind0405/blog#6]
> 每天学习，努力坚持，质变引起量变！
> 本来是说定的 100 天的计划，但是似乎每天在工作之余抽出的时间很难完成一个完整的主题，有时候一个主题需要学习好多天甚至更久，因此改为 100 个 issues 吧，Deadline 是 2020！
> 努力奔跑吧 💪💪💪 ！

### 基础
- [x] [数据类型基础](https://github.com/swiftwind0405/blog/issues/30)
- [x] [数据类型转换](https://github.com/swiftwind0405/blog/issues/40)
- [x] [作用域与作用域链](https://github.com/swiftwind0405/blog/issues/10)
- [x] [执行上下文](https://github.com/swiftwind0405/blog/issues/26)
- [x] [原型与原型链](https://github.com/swiftwind0405/blog/issues/4)
- [x] [DOM事件和事件流](https://github.com/swiftwind0405/blog/issues/29)
- [x] [Event-Loop](https://github.com/swiftwind0405/blog/issues/9)
- [x] [this](https://github.com/swiftwind0405/blog/issues/13)
- [x] [用 ES 规范去解释 this](https://github.com/swiftwind0405/blog/issues/54)
- [x] [闭包](https://github.com/swiftwind0405/blog/issues/3)
- [x] [Ajax](https://github.com/swiftwind0405/blog/issues/55)
- [x] [Fetch](https://github.com/swiftwind0405/blog/issues/66)
- [x] [循环遍历 in JavaScript](https://github.com/swiftwind0405/blog/issues/67)
- [x] [Array](https://github.com/swiftwind0405/blog/issues/2)
- [ ] [数组对象与arguments]()
- [x] [offset、scroll、client](https://github.com/swiftwind0405/blog/issues/52)
- [x] [垃圾回收机制](https://github.com/swiftwind0405/blog/issues/31)
- [x] [call、apply、bind 函数](https://github.com/swiftwind0405/blog/issues/11)
- [x] [赋值与深浅拷贝](https://github.com/swiftwind0405/blog/issues/20)
- [x] [对象基础](https://github.com/swiftwind0405/blog/issues/37)
- [x] [面向对象之继承](https://github.com/swiftwind0405/blog/issues/16)
- [x] [面向对象之封装](https://github.com/swiftwind0405/blog/issues/36)
- [x] [class (es6)](https://github.com/swiftwind0405/blog/issues/34)
- [x] [模块化](https://github.com/swiftwind0405/blog/issues/57)
- [x] [错误异常与捕获](https://github.com/swiftwind0405/blog/issues/58)
- [x] [Babel](https://github.com/swiftwind0405/blog/issues/5)
- [x] [ES6基础]()
- [ ] [requestAnimation]()
- [ ] [遍历对象的方法及区别]()
- [x] [Web Workers](https://github.com/swiftwind0405/blog/issues/74)
- [x] [浏览器中加载JavaScript的方式](https://github.com/swiftwind0405/blog/issues/70)

### 进阶
- [x] [数组拍平与数组去重](https://github.com/swiftwind0405/blog/issues/68)
- [x] [实现一个深拷贝](https://github.com/swiftwind0405/blog/issues/28)
- [ ] [深入EventLoop和浏览器渲染、帧动画、空闲回调的关系](https://github.com/swiftwind0405/blog/issues/64)
- [x] [防抖和节流](https://github.com/swiftwind0405/blog/issues/8)
- [ ] #75
- [ ] [高阶函数]()
- [ ] [new 的原理及实现](https://github.com/swiftwind0405/blog/issues/14)
- [ ] [call和apply的模拟实现]()
- [ ] [bind的模拟实现]()
- [ ] [ES6 深入知识]()
- [ ] [前端性能优化]()

### 异步
- [x] [异步的初步了解](https://github.com/swiftwind0405/blog/issues/12)
- [ ] [async/await]()
- [ ] [Promise](https://github.com/swiftwind0405/blog/issues/23)
- [ ] [手写实现完整的 Promise]()

## CSS
- [x] [flex 布局](https://github.com/swiftwind0405/blog/issues/18)
- [x] [BFC（块级格式化上下文）](https://github.com/swiftwind0405/blog/issues/25)
- [x] [层叠上下文](https://github.com/swiftwind0405/blog/issues/27)
- [x] [水平垂直居中](https://github.com/swiftwind0405/blog/issues/15)
- [x] [让一个元素消失的几种做法，有何不同，对子元素的影响]()

## 网络
- [x] [HTTP 和 HTTPS](https://github.com/swiftwind0405/blog/issues/17)
- [x] [options 请求、简单请求与复杂请求](https://github.com/swiftwind0405/blog/issues/65)
- [x] [TCP / IP ](https://github.com/swiftwind0405/blog/issues/62)

## React
- [x] [生命周期](https://github.com/swiftwind0405/blog/issues/35)
- [ ] [setState的执行机制](https://github.com/swiftwind0405/blog/issues/60)
- [x] [React-fiber]()
- [ ] [React的事件机制](https://github.com/swiftwind0405/blog/issues/61)
- [x] [React Hooks](https://github.com/swiftwind0405/blog/issues/51)
- [ ] [可靠React组件设计的7个准则](https://github.com/swiftwind0405/blog/issues/63)
- [ ] [实现一个简易的React]()
- [ ] [React-Router实现原理]()

## Webpack
- [x] [基础知识与简单配置](https://github.com/swiftwind0405/blog/issues/38)
- [x] [常用 loaders 与配置](https://github.com/swiftwind0405/blog/issues/39)
- [x] [常用 plugins 与配置](https://github.com/swiftwind0405/blog/issues/41)
- [ ] [多页面应用](https://github.com/swiftwind0405/blog/issues/43)
- [x] [Optimize 优化](https://github.com/swiftwind0405/blog/issues/44)
- [x] [Dev Tools 开发工具](https://github.com/swiftwind0405/blog/issues/42)
- [ ] [Tree Shaking](https://github.com/swiftwind0405/blog/issues/45)
- [ ] [Code Spliting 代码分割](https://github.com/swiftwind0405/blog/issues/46)
- [ ] [TypeScript 打包](https://github.com/swiftwind0405/blog/issues/49)
- [ ] [Library 库打包](https://github.com/swiftwind0405/blog/issues/47)
- [ ] [PWA 打包](https://github.com/swiftwind0405/blog/issues/48)
- [ ] [编写一个 loader](https://github.com/swiftwind0405/blog/issues/50)
- [ ] [实现一个简易的Webpack]()

## 算法
- [ ] [排序算法]()
- [ ] [洗牌算法]()
- [ ] [广度优先遍历]()

## 前端
- [x] [从输入一个URL到网页展示的过程](https://github.com/swiftwind0405/blog/issues/32)
- [x] [跨域](https://github.com/swiftwind0405/blog/issues/24)
- [x] [回流与重绘](https://github.com/swiftwind0405/blog/issues/33)
- [x] [缓存](https://github.com/swiftwind0405/blog/issues/19)
- [x] [Web 安全](https://github.com/swiftwind0405/blog/issues/21)

## Tips

以上所有主题，99.99% 非原创，个人只做收集总结归纳而已，仅供个人参考使用。

**Comment by swiftwind0405** [comment]
- [ ]

**Comment by swiftwind0405** [comment]
- [ ] xxx
- [x ]

**Comment by biyongzhi** [comment]
楼主，还在坚持吗

**Comment by swiftwind0405** [comment]
> 楼主，还在坚持吗

会继续坚持的，只是可能有时候一个主题要跨越几天，或者由于工作或者生活上的一些事插入。
不过基本每天早起学习，这个是保证的。
